export const NOTIFICATION_TYPE = {
  FILE_ASSIGNED: 'FILE_ASSIGNED',
  FILE_STATUS_CHANGED: 'FILE_STATUS_CHANGED',
  FILE_COMMENT_ADDED: 'FILE_COMMENT_ADDED',
  FILE_COMMENT_REPLIED: 'FILE_COMMENT_REPLIED',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  PROJECT_INVITATION: 'PROJECT_INVITATION',
  PROJECT_ROLE_CHANGED: 'PROJECT_ROLE_CHANGED',
} as const;

export const NOTIFICATION_RECIPIENT = {
  PROJECT_OWNER: 'PROJECT_OWNER',
  INVITED_USER: 'INVITED_USER',
} as const;
