const PAYMENT_TYPES = {
  HOURLY: 'per-hour',
  PER_PROJECT: 'per-project',
  PER_MONTH: 'per-month',
  PER_YEAR: 'per-year',
};

export const PAYMENT_TYPE_OPTIONS = [
  { label: 'Project', value: PAYMENT_TYPES.PER_PROJECT },
  { label: 'Hourly', value: PAYMENT_TYPES.HOURLY },
  { label: 'Monthly', value: PAYMENT_TYPES.PER_MONTH },
  { label: 'Yearly', value: PAYMENT_TYPES.PER_YEAR },
];

export const PAYMENT_TYPE_SHORTS = {
  [PAYMENT_TYPES.PER_PROJECT]: 'per project',
  [PAYMENT_TYPES.HOURLY]: 'per hour',
  [PAYMENT_TYPES.PER_MONTH]: 'per month',
  [PAYMENT_TYPES.PER_YEAR]: 'per year',
};

const PAYMENT_PREFERENCES = {
  CASH: 'cash',
  CREDIT_CARD: 'credit-card',
  BANK_TRANSFER: 'bank-transfer',
  PAYPAL: 'paypal',
  CRYPTO: 'crypto',
};

export const PAYMENT_PREFERENCES_LABELS = {
  [PAYMENT_PREFERENCES.CASH]: 'Cash',
  [PAYMENT_PREFERENCES.CREDIT_CARD]: 'Credit Card',
  [PAYMENT_PREFERENCES.BANK_TRANSFER]: 'Bank Transfer',
  [PAYMENT_PREFERENCES.PAYPAL]: 'PayPal',
  [PAYMENT_PREFERENCES.CRYPTO]: 'Crypto',
};

export const PAYMENT_PREFERENCES_ICONS = {
  [PAYMENT_PREFERENCES.CASH]: 'cash',
  [PAYMENT_PREFERENCES.CREDIT_CARD]: 'creditCard',
  [PAYMENT_PREFERENCES.BANK_TRANSFER]: 'bank',
  [PAYMENT_PREFERENCES.PAYPAL]: 'paypal',
  [PAYMENT_PREFERENCES.CRYPTO]: 'bitcoin',
} as const;

export const PAYMENT_PREFERENCE_OPTIONS = [
  { label: PAYMENT_PREFERENCES_LABELS[PAYMENT_PREFERENCES.CASH], value: PAYMENT_PREFERENCES.CASH },
  { label: PAYMENT_PREFERENCES_LABELS[PAYMENT_PREFERENCES.CREDIT_CARD], value: PAYMENT_PREFERENCES.CREDIT_CARD },
  { label: PAYMENT_PREFERENCES_LABELS[PAYMENT_PREFERENCES.BANK_TRANSFER], value: PAYMENT_PREFERENCES.BANK_TRANSFER },
  { label: PAYMENT_PREFERENCES_LABELS[PAYMENT_PREFERENCES.PAYPAL], value: PAYMENT_PREFERENCES.PAYPAL },
  { label: PAYMENT_PREFERENCES_LABELS[PAYMENT_PREFERENCES.CRYPTO], value: PAYMENT_PREFERENCES.CRYPTO },
];
