import { SeoPage } from './types';

// Auto-generated from marketplace SEO plan spreadsheet. Re-run: npm run import-seo-plan
export const SEO_PAGES: SeoPage[] = [
  {
    id: 1,
    type: 'compare',
    funnelSide: 'both',
    slug: 'clipping-marketplace-vs-video-editor-marketplace',
    title: 'Clipping Marketplace vs. Video Editor Marketplace: What\'s the Difference?',
    metaDescription: 'Clipping Marketplace vs. Video Editor Marketplace: What\'s the Difference?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'clipping marketplace vs video editor marketplace',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Already written — the disambiguation page',
    relatedSlugs: ['kreatli-vs-fiverr', 'kreatli-vs-whop-clips'],
  },
  {
    id: 2,
    type: 'compare',
    funnelSide: 'creator',
    slug: 'kreatli-vs-fiverr',
    title: 'Kreatli Marketplace vs. Fiverr for Hiring a Video Editor',
    metaDescription: 'Kreatli Marketplace vs. Fiverr for Hiring a Video Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'Fiverr alternative for video editors',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Lead with vetting + no 20% flat seller cut',
    relatedSlugs: ['clipping-marketplace-vs-video-editor-marketplace', 'kreatli-vs-upwork'],
  },
  {
    id: 3,
    type: 'compare',
    funnelSide: 'both',
    slug: 'kreatli-vs-upwork',
    title: 'Kreatli Marketplace vs. Upwork for Video Editing Work',
    metaDescription: 'Kreatli Marketplace vs. Upwork for Video Editing Work. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'Upwork vs Kreatli Marketplace for video editors',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Upwork\'s Connects system is the pain point to address',
    relatedSlugs: ['kreatli-vs-fiverr', 'kreatli-vs-discord-clipping-communities'],
  },
  {
    id: 4,
    type: 'compare',
    funnelSide: 'both',
    slug: 'kreatli-vs-discord-clipping-communities',
    title: 'Kreatli Marketplace vs. Discord Clipping Communities',
    metaDescription: 'Kreatli Marketplace vs. Discord Clipping Communities. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video editor marketplace vs Discord',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Trust/accountability angle — no ghosting, no scams',
    relatedSlugs: ['kreatli-vs-upwork', 'kreatli-vs-whop-clips'],
  },
  {
    id: 5,
    type: 'compare',
    funnelSide: 'clipper',
    slug: 'kreatli-vs-whop-clips',
    title: 'Kreatli Marketplace vs. Whop Clips (Content Rewards)',
    metaDescription: 'Kreatli Marketplace vs. Whop Clips (Content Rewards). Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'Whop clipping vs hiring an editor',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Pay-per-view vs fixed price for the work',
    relatedSlugs: ['kreatli-vs-discord-clipping-communities', 'clipping-marketplace-vs-video-editor-marketplace'],
  },
  {
    id: 6,
    type: 'compare',
    funnelSide: 'clipper',
    slug: 'kreatli-vs-vyro',
    title: 'Kreatli Marketplace vs. Vyro: Two Different Ways to Get Paid for Clips',
    metaDescription: 'Vyro pays clippers via CPM and content rewards. Kreatli Marketplace pays editors fixed project rates. Compare which model fits creators and clip editors.',
    primaryKeyword: 'Vyro alternative for editors',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'CPM payout risk vs guaranteed project pay',
    relatedSlugs: ['kreatli-vs-whop-clips', 'kreatli-vs-clipaffiliates', 'clipping-marketplace-vs-video-editor-marketplace'],
  },
  {
    id: 7,
    type: 'compare',
    funnelSide: 'clipper',
    slug: 'kreatli-vs-clipaffiliates',
    title: 'Kreatli Marketplace vs. ClipAffiliates',
    metaDescription: 'ClipAffiliates pays clippers via performance rewards. Kreatli Marketplace hires editors for fixed project pay. See which clipping model fits your goals.',
    primaryKeyword: 'ClipAffiliates alternative',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Smaller search volume — low effort, still worth it',
    relatedSlugs: ['kreatli-vs-vyro', 'kreatli-vs-whop-clips', 'clipping-marketplace-vs-video-editor-marketplace'],
  },
  {
    id: 8,
    type: 'compare',
    funnelSide: 'creator',
    slug: 'kreatli-vs-ai-clipping-tools',
    title: 'Do You Need an AI Clipping Tool or a Human Editor?',
    metaDescription: 'AI clipping tools generate fast drafts; human editors curate hooks and brand voice. Compare when to use OpusClip-style tools vs hiring on Kreatli Marketplace.',
    primaryKeyword: 'OpusClip alternative human editor',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Frame as complementary — AI generates, human curates/posts',
    relatedSlugs: ['kreatli-vs-hiring-in-house-editor', 'kreatli-vs-video-editing-agency', 'clipping-marketplace-vs-video-editor-marketplace'],
  },
  {
    id: 9,
    type: 'compare',
    funnelSide: 'creator',
    slug: 'kreatli-vs-hiring-in-house-editor',
    title: 'Kreatli Marketplace vs. Hiring a Full-Time Editor',
    metaDescription: 'Full-time editors cost $40k–$80k+/yr with fixed payroll. Kreatli Marketplace offers flexible freelance clip editors. Compare cost, speed, and scale.',
    primaryKeyword: 'freelance vs in-house video editor',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Cost/flexibility framing for growing channels',
    relatedSlugs: ['kreatli-vs-video-editing-agency', 'kreatli-vs-ai-clipping-tools', 'kreatli-vs-fiverr'],
  },
  {
    id: 10,
    type: 'compare',
    funnelSide: 'creator',
    slug: 'kreatli-vs-video-editing-agency',
    title: 'Kreatli Marketplace vs. a Video Editing Agency',
    metaDescription: 'Agencies add markup and account-manager queues. Kreatli Marketplace lets you hire clip editors directly at project rates. Compare speed, cost, and control.',
    primaryKeyword: 'video editing agency alternative',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Speed + cost vs agency overhead',
    relatedSlugs: ['kreatli-vs-hiring-in-house-editor', 'kreatli-vs-fiverr', 'kreatli-vs-upwork'],
  },
  {
    id: 11,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'what-is-a-clipper',
    title: 'What Is a Clipper? (Video Editing Definition)',
    metaDescription: 'A clipper edits long-form video into short clips — but the term means two different jobs. Learn freelance clip editing vs. CPM content rewards.',
    primaryKeyword: 'what is a clipper',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    notes: 'Short, definitional — target featured snippet',
    relatedSlugs: ['what-is-a-clipping-marketplace', 'cpm-meaning-clipping', 'clipping-marketplace-vs-video-editor-marketplace'],
  },
  {
    id: 12,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'what-is-a-clipping-marketplace',
    title: 'What Is a Clipping Marketplace?',
    metaDescription: 'A clipping marketplace connects clippers and creators — but models differ. Compare content-rewards CPM platforms vs. editor hiring marketplaces.',
    primaryKeyword: 'what is a clipping marketplace',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    notes: 'Short, definitional — target featured snippet',
    relatedSlugs: ['what-is-a-clipper', 'cpm-meaning-clipping', 'clipping-marketplace-vs-video-editor-marketplace'],
  },
  {
    id: 13,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'cpm-meaning-clipping',
    title: 'CPM Explained (Cost Per Mille / Per 1,000 Views)',
    metaDescription: 'CPM in clipping means pay per 1,000 views on content-rewards campaigns. See how CPM differs from fixed project pay when hiring clip editors.',
    primaryKeyword: 'CPM meaning clipping',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    notes: 'Short, definitional — target featured snippet',
    relatedSlugs: ['what-is-a-clipper', 'what-is-a-clipping-marketplace', 'kreatli-vs-whop-clips'],
  },
  {
    id: 14,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'what-is-b-roll',
    title: 'What Is B-Roll?',
    metaDescription: 'B-roll is supplementary footage layered over A-roll to add visual interest in short-form clips. Learn sources, examples, and briefing tips for editors.',
    primaryKeyword: 'what is b-roll',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    notes: 'Short, definitional — target featured snippet',
    relatedSlugs: ['jump-cut-definition', 'what-is-a-clipper', 'podcast-clipping-meaning'],
  },
  {
    id: 15,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'jump-cut-definition',
    title: 'What Is a Jump Cut?',
    metaDescription: 'A jump cut removes time from the same shot, tightening talking-head clips for TikTok and Shorts. Definition, examples, and editing tips.',
    primaryKeyword: 'jump cut definition',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    notes: 'Short, definitional — target featured snippet',
    relatedSlugs: ['what-is-b-roll', 'what-is-a-clipper', 'video-hook-first-3-seconds'],
  },
  {
    id: 16,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'talking-head-edit',
    title: 'What Is a Talking-Head Edit?',
    metaDescription: 'What Is a Talking-Head Edit?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'talking head edit',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 17,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'podcast-clipping-meaning',
    title: 'What Is Podcast Clipping?',
    metaDescription: 'What Is Podcast Clipping?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'podcast clipping meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 18,
    type: 'glossary',
    funnelSide: 'both',
    slug: '9:16-aspect-ratio-video',
    title: 'Vertical Video / 9:16 Aspect Ratio Explained',
    metaDescription: 'Vertical Video / 9:16 Aspect Ratio Explained. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: '9:16 aspect ratio video',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 19,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'video-hook-first-3-seconds',
    title: 'The Hook: Why the First 3 Seconds Matter',
    metaDescription: 'The Hook: Why the First 3 Seconds Matter. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video hook first 3 seconds',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 20,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'video-retention-rate-meaning',
    title: 'What Is Retention Rate in Short-Form Video?',
    metaDescription: 'What Is Retention Rate in Short-Form Video?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video retention rate meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 21,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'burned-in-captions-meaning',
    title: 'What Are Burned-In Captions?',
    metaDescription: 'What Are Burned-In Captions?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'burned in captions meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 22,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'l-cut-j-cut-editing',
    title: 'L-Cut and J-Cut Explained',
    metaDescription: 'L-Cut and J-Cut Explained. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'L-cut J-cut editing',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 23,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'motion-graphics-short-form-video',
    title: 'What Are Motion Graphics (for Short-Form Video)?',
    metaDescription: 'What Are Motion Graphics (for Short-Form Video)?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'motion graphics short form video',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 24,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'royalty-free-music-for-clips',
    title: 'Royalty-Free Music Licensing for Clips, Explained',
    metaDescription: 'Royalty-Free Music Licensing for Clips, Explained. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'royalty free music for clips',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 25,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'repurposing-content-meaning',
    title: 'What Does \'Repurposing Content\' Mean?',
    metaDescription: 'What Does \'Repurposing Content\' Mean?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'repurposing content meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 26,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'faceless-channel-meaning',
    title: 'What Is a Faceless Channel?',
    metaDescription: 'What Is a Faceless Channel?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'faceless channel meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 27,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'escrow-payment-freelance-meaning',
    title: 'What Is Escrow Payment (Freelance Marketplace Term)?',
    metaDescription: 'What Is Escrow Payment (Freelance Marketplace Term)?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'escrow payment freelance meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 28,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'milestone-payment-freelance',
    title: 'What Is a Milestone Payment?',
    metaDescription: 'What Is a Milestone Payment?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'milestone payment freelance',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 29,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'gig-vs-project-vs-retainer',
    title: 'Gig vs. Project vs. Retainer: What\'s the Difference?',
    metaDescription: 'Gig vs. Project vs. Retainer: What\'s the Difference?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'gig vs project vs retainer',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 30,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'video-editing-turnaround-time',
    title: 'What Is Turnaround Time in Video Editing?',
    metaDescription: 'What Is Turnaround Time in Video Editing?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video editing turnaround time',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 31,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'cost-to-hire-a-video-editor',
    title: 'How Much Does It Cost to Hire a Video Editor in 2026?',
    metaDescription: 'Video editor costs in 2026: $15–$75 per clip or $800–$3,500/mo retainers. Benchmarks for podcast, Shorts, and TikTok clipping on Kreatli Marketplace.',
    primaryKeyword: 'cost to hire a video editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['hire-a-podcast-clip-editor', 'kreatli-vs-fiverr', 'kreatli-vs-hiring-in-house-editor'],
  },
  {
    id: 32,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'how-to-brief-a-video-editor',
    title: 'How to Brief a Video Editor (So You Don\'t Get Bad Cuts Back)',
    metaDescription: 'Brief a video editor with clear goals, source files, style references, deliverables, and feedback rules so your first clipping batch comes back usable.',
    primaryKeyword: 'how to brief a video editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['how-to-write-a-video-editing-job-post', 'vet-a-freelance-video-editor', 'hire-a-youtube-shorts-editor'],
  },
  {
    id: 33,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'find-a-tiktok-editor',
    title: 'How to Find a TikTok or Reels Editor',
    metaDescription: 'Find a TikTok or Reels editor who understands hooks, captions, pacing, and retention. Learn where to look, what to test, and how to hire.',
    primaryKeyword: 'find a TikTok editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['hire-a-tiktok-editor', 'hire-an-instagram-reels-editor', 'vet-a-freelance-video-editor'],
  },
  {
    id: 34,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'repurpose-podcast-into-clips',
    title: 'How to Repurpose a Podcast Into Short Clips',
    metaDescription: 'Repurpose podcasts into TikTok, Reels, and Shorts: find hooks, edit vertical clips, and hire a podcast clip editor on Kreatli Marketplace.',
    primaryKeyword: 'repurpose podcast into clips',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['hire-a-podcast-clip-editor', 'cost-to-hire-a-video-editor', 'what-is-a-clipper'],
  },
  {
    id: 35,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'ai-clipping-tool-vs-human-editor',
    title: 'AI Clipping Tool vs. Human Editor: How to Choose',
    metaDescription: 'AI Clipping Tool vs. Human Editor: How to Choose. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'AI clipping tool vs human editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 36,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'vet-a-freelance-video-editor',
    title: 'How to Vet a Freelance Video Editor Before Hiring',
    metaDescription: 'Vet freelance video editors with portfolio checks, paid trials, and clipping-specific criteria before you scale on Kreatli Marketplace.',
    primaryKeyword: 'vet a freelance video editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['kreatli-vs-fiverr', 'kreatli-vs-upwork', 'cost-to-hire-a-video-editor'],
  },
  {
    id: 37,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'how-to-write-a-video-editing-job-post',
    title: 'How to Write a Job Post That Attracts Good Clip Editors',
    metaDescription: 'Write a video editing job post that attracts qualified clip editors: scope, budget, examples, deliverables, timeline, and trial batch template.',
    primaryKeyword: 'how to write a video editing job post',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['how-to-brief-a-video-editor', 'cost-to-hire-a-video-editor', 'hire-a-youtube-shorts-editor'],
  },
  {
    id: 38,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'scale-youtube-shorts-production',
    title: 'How to Scale Your YouTube Shorts Production Without Burning Out',
    metaDescription: 'How to Scale Your YouTube Shorts Production Without Burning Out. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'scale YouTube Shorts production',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 39,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'become-a-freelance-video-editor',
    title: 'How to Become a Freelance Video Editor With No Experience',
    metaDescription: 'Become a freelance clip editor: learn short-form skills, build vertical samples, and join Kreatli Marketplace for fixed project pay gigs.',
    primaryKeyword: 'become a freelance video editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['find-first-video-editing-client', 'how-to-price-video-editing-services', 'what-is-a-clipper'],
  },
  {
    id: 40,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'how-to-price-video-editing-services',
    title: 'How to Price Your Video Editing Services (2026 Rate Guide)',
    metaDescription: '2026 clip editing rates: $15–$65+ per vertical clip and retainer math for podcast, Shorts, and TikTok work on Kreatli Marketplace.',
    primaryKeyword: 'how to price video editing services',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['find-first-video-editing-client', 'fiverr-vs-upwork-for-video-editors', 'cost-to-hire-a-video-editor'],
  },
  {
    id: 41,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'video-editing-portfolio-no-clients',
    title: 'How to Build a Portfolio Before You Have Clients',
    metaDescription: 'Build a video editing portfolio with no clients using practice footage, before-and-after clips, niche samples, and clear case-study writeups.',
    primaryKeyword: 'video editing portfolio no clients',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['become-a-freelance-video-editor', 'find-first-video-editing-client', 'video-editing-proposal-template'],
  },
  {
    id: 42,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'find-first-video-editing-client',
    title: 'How to Find Your First Clip Editing Client',
    metaDescription: 'Land your first clip editing client with niche samples, starter rates, and Kreatli Marketplace job applications — fixed project pay, not CPM.',
    primaryKeyword: 'find first video editing client',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['become-a-freelance-video-editor', 'how-to-price-video-editing-services', 'what-is-a-clipper'],
  },
  {
    id: 43,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'video-editing-proposal-template',
    title: 'How to Write a Winning Proposal for Video Editing Gigs',
    metaDescription: 'Use video editing proposal templates for clipping gigs, trial batches, retainers, and creator job posts so clients can trust you fast.',
    primaryKeyword: 'video editing proposal template',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['video-editing-portfolio-no-clients', 'find-first-video-editing-client', 'how-to-price-video-editing-services'],
  },
  {
    id: 44,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'best-video-editing-software-for-clippers',
    title: 'Best Software for Clip Editors in 2026',
    metaDescription: 'Best Software for Clip Editors in 2026. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'best video editing software for clippers',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 45,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'niche-video-editor-specialization',
    title: 'How to Specialize as a Niche Video Editor (Gaming, Podcast, etc.)',
    metaDescription: 'How to Specialize as a Niche Video Editor (Gaming, Podcast, etc.). Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'niche video editor specialization',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 46,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'fiverr-vs-upwork-for-video-editors',
    title: 'Fiverr vs. Upwork vs. Kreatli Marketplace: Where Should Editors Actually Start?',
    metaDescription: 'Fiverr vs Upwork vs Kreatli Marketplace for clip editors: fees, buyer intent, and where to build repeat clipping clients in 2026.',
    primaryKeyword: 'Fiverr vs Upwork for video editors',
    searchIntent: 'informational',
    wave: 1,
    status: 'published',
    relatedSlugs: ['kreatli-vs-fiverr', 'kreatli-vs-upwork', 'how-to-price-video-editing-services'],
  },
  {
    id: 47,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-podcast-clip-editor',
    title: 'Hire a Podcast Clip Editor',
    metaDescription: 'Hire a vetted podcast clip editor on Kreatli Marketplace. Fixed project pay, vertical clips for TikTok, Reels, and Shorts — delivered to your channels.',
    primaryKeyword: 'hire a podcast clip editor',
    searchIntent: 'transactional',
    wave: 2,
    status: 'published',
    ctaHref: '/jobs/create',
    relatedSlugs: ['repurpose-podcast-into-clips', 'cost-to-hire-a-video-editor', 'what-is-a-clipper'],
  },
  {
    id: 48,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-twitch-vod-editor',
    title: 'Hire a Twitch VOD Editor',
    metaDescription: 'Hire a Twitch VOD editor to turn long streams into Shorts, TikToks, Reels, highlight videos, and repeatable weekly clip batches.',
    primaryKeyword: 'hire a Twitch VOD editor',
    searchIntent: 'transactional',
    wave: 2,
    status: 'published',
    ctaHref: '/jobs/create',
    relatedSlugs: ['hire-a-livestream-editor', 'hire-a-gaming-highlight-editor', 'hire-a-youtube-shorts-editor'],
  },
  {
    id: 49,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-youtube-shorts-editor',
    title: 'Hire a YouTube Shorts Editor',
    metaDescription: 'Hire a YouTube Shorts editor for hook-first vertical clips. Post a job on Kreatli Marketplace, review profiles, and scale Shorts at fixed project rates.',
    primaryKeyword: 'hire a YouTube Shorts editor',
    searchIntent: 'transactional',
    wave: 2,
    status: 'published',
    ctaHref: '/jobs/create',
    relatedSlugs: ['hire-a-tiktok-editor', 'kreatli-vs-ai-clipping-tools', 'kreatli-vs-hiring-in-house-editor'],
  },
  {
    id: 50,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-gaming-highlight-editor',
    title: 'Hire a Gaming Highlight Editor',
    metaDescription: 'Hire a gaming highlight editor for stream moments, gameplay clips, captions, sound design, meme timing, and Shorts-ready deliverables.',
    primaryKeyword: 'hire a gaming highlight editor',
    searchIntent: 'transactional',
    wave: 2,
    status: 'published',
    ctaHref: '/jobs/create',
    relatedSlugs: ['hire-a-twitch-vod-editor', 'hire-a-livestream-editor', 'cost-to-hire-a-video-editor'],
  },
  {
    id: 51,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-tiktok-editor',
    title: 'Hire a TikTok Content Editor',
    metaDescription: 'Hire a TikTok content editor for native vertical clips. Kreatli Marketplace connects you with editors at fixed project pay — you post from your account.',
    primaryKeyword: 'hire a TikTok editor',
    searchIntent: 'transactional',
    wave: 2,
    status: 'published',
    ctaHref: '/jobs/create',
    relatedSlugs: ['hire-a-youtube-shorts-editor', 'kreatli-vs-fiverr', 'clipping-marketplace-vs-video-editor-marketplace'],
  },
  {
    id: 52,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-an-instagram-reels-editor',
    title: 'Hire an Instagram Reels Editor',
    metaDescription: 'Hire an Instagram Reels editor for hook-first vertical clips, burned-in captions, brand consistency, retention, and weekly content batches.',
    primaryKeyword: 'hire an Instagram Reels editor',
    searchIntent: 'transactional',
    wave: 2,
    status: 'published',
    ctaHref: '/jobs/create',
    relatedSlugs: ['hire-a-tiktok-editor', 'find-a-tiktok-editor', 'hire-a-youtube-shorts-editor'],
  },
  {
    id: 53,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-faceless-channel-editor',
    title: 'Hire a Faceless YouTube Channel Editor',
    metaDescription: 'Hire a faceless YouTube channel editor for voiceover timing, stock footage, B-roll, captions, AI-assisted assets, and repeatable clip output.',
    primaryKeyword: 'hire a faceless channel editor',
    searchIntent: 'transactional',
    wave: 2,
    status: 'published',
    ctaHref: '/jobs/create',
    relatedSlugs: ['what-is-b-roll', 'kreatli-vs-ai-clipping-tools', 'cost-to-hire-a-video-editor'],
  },
  {
    id: 54,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-livestream-editor',
    title: 'Hire a Livestream VOD Editor',
    metaDescription: 'Hire a livestream editor to repurpose VODs into highlight clips, Shorts, TikToks, Reels, and a consistent post-stream content pipeline.',
    primaryKeyword: 'hire a livestream editor',
    searchIntent: 'transactional',
    wave: 2,
    status: 'published',
    ctaHref: '/jobs/create',
    relatedSlugs: ['hire-a-twitch-vod-editor', 'hire-a-gaming-highlight-editor', 'how-to-brief-a-video-editor'],
  },
  {
    id: 55,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-course-content-editor',
    title: 'Hire a Course or Coaching Content Editor',
    metaDescription: 'Hire a Course or Coaching Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a course content editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 56,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-webinar-clip-editor',
    title: 'Hire a Webinar-to-Clips Editor',
    metaDescription: 'Hire a Webinar-to-Clips Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a webinar clip editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 57,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-comedy-skit-editor',
    title: 'Hire a Comedy/Skit Content Editor',
    metaDescription: 'Hire a Comedy/Skit Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a comedy skit editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 58,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-fitness-content-editor',
    title: 'Hire a Fitness Content Editor',
    metaDescription: 'Hire a Fitness Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a fitness content editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 59,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-finance-content-editor',
    title: 'Hire a Finance/Finfluencer Content Editor',
    metaDescription: 'Hire a Finance/Finfluencer Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a finance content editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 60,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-real-estate-video-editor',
    title: 'Hire a Real Estate Video Editor',
    metaDescription: 'Hire a Real Estate Video Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a real estate video editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 61,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-musician-content-editor',
    title: 'Hire a Musician/Artist Content Editor',
    metaDescription: 'Hire a Musician/Artist Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a musician content editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 62,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-b2b-video-editor',
    title: 'Hire a B2B/SaaS Video Editor',
    metaDescription: 'Hire a B2B/SaaS Video Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a B2B video editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 63,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-motivational-content-editor',
    title: 'Hire a Motivational/Quotes Content Editor',
    metaDescription: 'Hire a Motivational/Quotes Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a motivational content editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 64,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-beauty-lifestyle-editor',
    title: 'Hire a Beauty/Lifestyle Content Editor',
    metaDescription: 'Hire a Beauty/Lifestyle Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a beauty lifestyle editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 65,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-true-crime-content-editor',
    title: 'Hire a True Crime/Storytelling Content Editor',
    metaDescription: 'Hire a True Crime/Storytelling Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a true crime content editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
  {
    id: 66,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-linkedin-video-editor',
    title: 'Hire a LinkedIn Video Content Editor',
    metaDescription: 'Hire a LinkedIn Video Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a LinkedIn video editor',
    searchIntent: 'transactional',
    wave: 3,
    status: 'draft',
    ctaHref: '/jobs/create',
  },
];
