import { SeoPage } from './types';

// Auto-generated from marketplace SEO plan spreadsheet. Re-run: npm run import-seo-plan
export const SEO_PAGES: SeoPage[] = [
  {
    id: 1,
    type: 'compare',
    funnelSide: 'both',
    slug: 'clipping-marketplace-vs-video-editor-marketplace',
    title: 'Clipping Marketplace vs. Video Editor Marketplace: What\'s the Difference?',
    metaDescription: 'Clipping Marketplace vs. Video Editor Marketplace: What\'s the Difference?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'clipping marketplace vs video editor marketplace',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Already written — the disambiguation page',
    relatedSlugs: ['kreatli-vs-fiverr', 'kreatli-vs-whop-clips'],
  },
  {
    id: 2,
    type: 'compare',
    funnelSide: 'creator',
    slug: 'kreatli-vs-fiverr',
    title: 'Kreatli Marketplace vs. Fiverr for Hiring a Video Editor',
    metaDescription: 'Kreatli Marketplace vs. Fiverr for Hiring a Video Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'Fiverr alternative for video editors',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Lead with vetting + no 20% flat seller cut',
    relatedSlugs: ['clipping-marketplace-vs-video-editor-marketplace', 'kreatli-vs-upwork'],
  },
  {
    id: 3,
    type: 'compare',
    funnelSide: 'both',
    slug: 'kreatli-vs-upwork',
    title: 'Kreatli Marketplace vs. Upwork for Video Editing Work',
    metaDescription: 'Kreatli Marketplace vs. Upwork for Video Editing Work. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'Upwork vs Kreatli Marketplace for video editors',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Upwork\'s Connects system is the pain point to address',
    relatedSlugs: ['kreatli-vs-fiverr', 'kreatli-vs-discord-clipping-communities'],
  },
  {
    id: 4,
    type: 'compare',
    funnelSide: 'both',
    slug: 'kreatli-vs-discord-clipping-communities',
    title: 'Kreatli Marketplace vs. Discord Clipping Communities',
    metaDescription: 'Kreatli Marketplace vs. Discord Clipping Communities. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video editor marketplace vs Discord',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Trust/accountability angle — no ghosting, no scams',
    relatedSlugs: ['kreatli-vs-upwork', 'kreatli-vs-whop-clips'],
  },
  {
    id: 5,
    type: 'compare',
    funnelSide: 'clipper',
    slug: 'kreatli-vs-whop-clips',
    title: 'Kreatli Marketplace vs. Whop Clips (Content Rewards)',
    metaDescription: 'Kreatli Marketplace vs. Whop Clips (Content Rewards). Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'Whop clipping vs hiring an editor',
    searchIntent: 'commercial',
    wave: 1,
    status: 'published',
    notes: 'Pay-per-view vs fixed price for the work',
    relatedSlugs: ['kreatli-vs-discord-clipping-communities', 'clipping-marketplace-vs-video-editor-marketplace'],
  },
  {
    id: 6,
    type: 'compare',
    funnelSide: 'clipper',
    slug: 'kreatli-vs-vyro',
    title: 'Kreatli Marketplace vs. Vyro: Two Different Ways to Get Paid for Clips',
    metaDescription: 'Kreatli Marketplace vs. Vyro: Two Different Ways to Get Paid for Clips. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'Vyro alternative for editors',
    searchIntent: 'commercial',
    wave: 1,
    status: 'draft',
    notes: 'CPM payout risk vs guaranteed project pay',
  },
  {
    id: 7,
    type: 'compare',
    funnelSide: 'clipper',
    slug: 'kreatli-vs-clipaffiliates',
    title: 'Kreatli Marketplace vs. ClipAffiliates',
    metaDescription: 'Kreatli Marketplace vs. ClipAffiliates. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'ClipAffiliates alternative',
    searchIntent: 'commercial',
    wave: 1,
    status: 'draft',
    notes: 'Smaller search volume — low effort, still worth it',
  },
  {
    id: 8,
    type: 'compare',
    funnelSide: 'creator',
    slug: 'kreatli-vs-ai-clipping-tools',
    title: 'Do You Need an AI Clipping Tool or a Human Editor?',
    metaDescription: 'Do You Need an AI Clipping Tool or a Human Editor?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'OpusClip alternative human editor',
    searchIntent: 'commercial',
    wave: 1,
    status: 'draft',
    notes: 'Frame as complementary — AI generates, human curates/posts',
  },
  {
    id: 9,
    type: 'compare',
    funnelSide: 'creator',
    slug: 'kreatli-vs-hiring-in-house-editor',
    title: 'Kreatli Marketplace vs. Hiring a Full-Time Editor',
    metaDescription: 'Kreatli Marketplace vs. Hiring a Full-Time Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'freelance vs in-house video editor',
    searchIntent: 'commercial',
    wave: 1,
    status: 'draft',
    notes: 'Cost/flexibility framing for growing channels',
  },
  {
    id: 10,
    type: 'compare',
    funnelSide: 'creator',
    slug: 'kreatli-vs-video-editing-agency',
    title: 'Kreatli Marketplace vs. a Video Editing Agency',
    metaDescription: 'Kreatli Marketplace vs. a Video Editing Agency. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video editing agency alternative',
    searchIntent: 'commercial',
    wave: 1,
    status: 'draft',
    notes: 'Speed + cost vs agency overhead',
  },
  {
    id: 11,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'what-is-a-clipper',
    title: 'What Is a Clipper? (Video Editing Definition)',
    metaDescription: 'What Is a Clipper? (Video Editing Definition). Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'what is a clipper',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 12,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'what-is-a-clipping-marketplace',
    title: 'What Is a Clipping Marketplace?',
    metaDescription: 'What Is a Clipping Marketplace?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'what is a clipping marketplace',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 13,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'cpm-meaning-clipping',
    title: 'CPM Explained (Cost Per Mille / Per 1,000 Views)',
    metaDescription: 'CPM Explained (Cost Per Mille / Per 1,000 Views). Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'CPM meaning clipping',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 14,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'what-is-b-roll',
    title: 'What Is B-Roll?',
    metaDescription: 'What Is B-Roll?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'what is b-roll',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 15,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'jump-cut-definition',
    title: 'What Is a Jump Cut?',
    metaDescription: 'What Is a Jump Cut?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'jump cut definition',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 16,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'talking-head-edit',
    title: 'What Is a Talking-Head Edit?',
    metaDescription: 'What Is a Talking-Head Edit?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'talking head edit',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 17,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'podcast-clipping-meaning',
    title: 'What Is Podcast Clipping?',
    metaDescription: 'What Is Podcast Clipping?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'podcast clipping meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 18,
    type: 'glossary',
    funnelSide: 'both',
    slug: '9:16-aspect-ratio-video',
    title: 'Vertical Video / 9:16 Aspect Ratio Explained',
    metaDescription: 'Vertical Video / 9:16 Aspect Ratio Explained. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: '9:16 aspect ratio video',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 19,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'video-hook-first-3-seconds',
    title: 'The Hook: Why the First 3 Seconds Matter',
    metaDescription: 'The Hook: Why the First 3 Seconds Matter. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video hook first 3 seconds',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 20,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'video-retention-rate-meaning',
    title: 'What Is Retention Rate in Short-Form Video?',
    metaDescription: 'What Is Retention Rate in Short-Form Video?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video retention rate meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 21,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'burned-in-captions-meaning',
    title: 'What Are Burned-In Captions?',
    metaDescription: 'What Are Burned-In Captions?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'burned in captions meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 22,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'l-cut-j-cut-editing',
    title: 'L-Cut and J-Cut Explained',
    metaDescription: 'L-Cut and J-Cut Explained. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'L-cut J-cut editing',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 23,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'motion-graphics-short-form-video',
    title: 'What Are Motion Graphics (for Short-Form Video)?',
    metaDescription: 'What Are Motion Graphics (for Short-Form Video)?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'motion graphics short form video',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 24,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'royalty-free-music-for-clips',
    title: 'Royalty-Free Music Licensing for Clips, Explained',
    metaDescription: 'Royalty-Free Music Licensing for Clips, Explained. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'royalty free music for clips',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 25,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'repurposing-content-meaning',
    title: 'What Does \'Repurposing Content\' Mean?',
    metaDescription: 'What Does \'Repurposing Content\' Mean?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'repurposing content meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 26,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'faceless-channel-meaning',
    title: 'What Is a Faceless Channel?',
    metaDescription: 'What Is a Faceless Channel?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'faceless channel meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 27,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'escrow-payment-freelance-meaning',
    title: 'What Is Escrow Payment (Freelance Marketplace Term)?',
    metaDescription: 'What Is Escrow Payment (Freelance Marketplace Term)?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'escrow payment freelance meaning',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 28,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'milestone-payment-freelance',
    title: 'What Is a Milestone Payment?',
    metaDescription: 'What Is a Milestone Payment?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'milestone payment freelance',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 29,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'gig-vs-project-vs-retainer',
    title: 'Gig vs. Project vs. Retainer: What\'s the Difference?',
    metaDescription: 'Gig vs. Project vs. Retainer: What\'s the Difference?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'gig vs project vs retainer',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 30,
    type: 'glossary',
    funnelSide: 'both',
    slug: 'video-editing-turnaround-time',
    title: 'What Is Turnaround Time in Video Editing?',
    metaDescription: 'What Is Turnaround Time in Video Editing?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video editing turnaround time',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
    notes: 'Short, definitional — target featured snippet',
  },
  {
    id: 31,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'cost-to-hire-a-video-editor',
    title: 'How Much Does It Cost to Hire a Video Editor in 2026?',
    metaDescription: 'How Much Does It Cost to Hire a Video Editor in 2026?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'cost to hire a video editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 32,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'how-to-brief-a-video-editor',
    title: 'How to Brief a Video Editor (So You Don\'t Get Bad Cuts Back)',
    metaDescription: 'How to Brief a Video Editor (So You Don\'t Get Bad Cuts Back). Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'how to brief a video editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 33,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'find-a-tiktok-editor',
    title: 'How to Find a TikTok or Reels Editor',
    metaDescription: 'How to Find a TikTok or Reels Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'find a TikTok editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 34,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'repurpose-podcast-into-clips',
    title: 'How to Repurpose a Podcast Into Short Clips',
    metaDescription: 'How to Repurpose a Podcast Into Short Clips. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'repurpose podcast into clips',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 35,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'ai-clipping-tool-vs-human-editor',
    title: 'AI Clipping Tool vs. Human Editor: How to Choose',
    metaDescription: 'AI Clipping Tool vs. Human Editor: How to Choose. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'AI clipping tool vs human editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 36,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'vet-a-freelance-video-editor',
    title: 'How to Vet a Freelance Video Editor Before Hiring',
    metaDescription: 'How to Vet a Freelance Video Editor Before Hiring. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'vet a freelance video editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 37,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'how-to-write-a-video-editing-job-post',
    title: 'How to Write a Job Post That Attracts Good Clip Editors',
    metaDescription: 'How to Write a Job Post That Attracts Good Clip Editors. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'how to write a video editing job post',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 38,
    type: 'guide',
    funnelSide: 'creator',
    slug: 'scale-youtube-shorts-production',
    title: 'How to Scale Your YouTube Shorts Production Without Burning Out',
    metaDescription: 'How to Scale Your YouTube Shorts Production Without Burning Out. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'scale YouTube Shorts production',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 39,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'become-a-freelance-video-editor',
    title: 'How to Become a Freelance Video Editor With No Experience',
    metaDescription: 'How to Become a Freelance Video Editor With No Experience. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'become a freelance video editor',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 40,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'how-to-price-video-editing-services',
    title: 'How to Price Your Video Editing Services (2026 Rate Guide)',
    metaDescription: 'How to Price Your Video Editing Services (2026 Rate Guide). Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'how to price video editing services',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 41,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'video-editing-portfolio-no-clients',
    title: 'How to Build a Portfolio Before You Have Clients',
    metaDescription: 'How to Build a Portfolio Before You Have Clients. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video editing portfolio no clients',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 42,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'find-first-video-editing-client',
    title: 'How to Find Your First Clip Editing Client',
    metaDescription: 'How to Find Your First Clip Editing Client. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'find first video editing client',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 43,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'video-editing-proposal-template',
    title: 'How to Write a Winning Proposal for Video Editing Gigs',
    metaDescription: 'How to Write a Winning Proposal for Video Editing Gigs. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'video editing proposal template',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 44,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'best-video-editing-software-for-clippers',
    title: 'Best Software for Clip Editors in 2026',
    metaDescription: 'Best Software for Clip Editors in 2026. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'best video editing software for clippers',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 45,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'niche-video-editor-specialization',
    title: 'How to Specialize as a Niche Video Editor (Gaming, Podcast, etc.)',
    metaDescription: 'How to Specialize as a Niche Video Editor (Gaming, Podcast, etc.). Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'niche video editor specialization',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 46,
    type: 'guide',
    funnelSide: 'clipper',
    slug: 'fiverr-vs-upwork-for-video-editors',
    title: 'Fiverr vs. Upwork vs. Kreatli Marketplace: Where Should Editors Actually Start?',
    metaDescription: 'Fiverr vs. Upwork vs. Kreatli Marketplace: Where Should Editors Actually Start?. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'Fiverr vs Upwork for video editors',
    searchIntent: 'informational',
    wave: 1,
    status: 'draft',
  },
  {
    id: 47,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-podcast-clip-editor',
    title: 'Hire a Podcast Clip Editor',
    metaDescription: 'Hire a Podcast Clip Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a podcast clip editor',
    searchIntent: 'transactional',
    wave: 2,
    dependency: 'Needs 5+ active podcast-niche listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 48,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-twitch-vod-editor',
    title: 'Hire a Twitch VOD Editor',
    metaDescription: 'Hire a Twitch VOD Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a Twitch VOD editor',
    searchIntent: 'transactional',
    wave: 2,
    dependency: 'Needs 5+ active Twitch-niche listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 49,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-youtube-shorts-editor',
    title: 'Hire a YouTube Shorts Editor',
    metaDescription: 'Hire a YouTube Shorts Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a YouTube Shorts editor',
    searchIntent: 'transactional',
    wave: 2,
    dependency: 'Needs 5+ active Shorts-niche listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 50,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-gaming-highlight-editor',
    title: 'Hire a Gaming Highlight Editor',
    metaDescription: 'Hire a Gaming Highlight Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a gaming highlight editor',
    searchIntent: 'transactional',
    wave: 2,
    dependency: 'Needs 5+ active gaming-niche listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 51,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-tiktok-editor',
    title: 'Hire a TikTok Content Editor',
    metaDescription: 'Hire a TikTok Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a TikTok editor',
    searchIntent: 'transactional',
    wave: 2,
    dependency: 'Needs 5+ active TikTok-niche listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 52,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-an-instagram-reels-editor',
    title: 'Hire an Instagram Reels Editor',
    metaDescription: 'Hire an Instagram Reels Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire an Instagram Reels editor',
    searchIntent: 'transactional',
    wave: 2,
    dependency: 'Needs 5+ active Reels-niche listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 53,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-faceless-channel-editor',
    title: 'Hire a Faceless YouTube Channel Editor',
    metaDescription: 'Hire a Faceless YouTube Channel Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a faceless channel editor',
    searchIntent: 'transactional',
    wave: 2,
    dependency: 'Needs 5+ active listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 54,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-livestream-editor',
    title: 'Hire a Livestream VOD Editor',
    metaDescription: 'Hire a Livestream VOD Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a livestream editor',
    searchIntent: 'transactional',
    wave: 2,
    dependency: 'Needs 5+ active listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 55,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-course-content-editor',
    title: 'Hire a Course or Coaching Content Editor',
    metaDescription: 'Hire a Course or Coaching Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a course content editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 56,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-webinar-clip-editor',
    title: 'Hire a Webinar-to-Clips Editor',
    metaDescription: 'Hire a Webinar-to-Clips Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a webinar clip editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 57,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-comedy-skit-editor',
    title: 'Hire a Comedy/Skit Content Editor',
    metaDescription: 'Hire a Comedy/Skit Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a comedy skit editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 58,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-fitness-content-editor',
    title: 'Hire a Fitness Content Editor',
    metaDescription: 'Hire a Fitness Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a fitness content editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 59,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-finance-content-editor',
    title: 'Hire a Finance/Finfluencer Content Editor',
    metaDescription: 'Hire a Finance/Finfluencer Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a finance content editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 60,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-real-estate-video-editor',
    title: 'Hire a Real Estate Video Editor',
    metaDescription: 'Hire a Real Estate Video Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a real estate video editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 61,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-musician-content-editor',
    title: 'Hire a Musician/Artist Content Editor',
    metaDescription: 'Hire a Musician/Artist Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a musician content editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 62,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-b2b-video-editor',
    title: 'Hire a B2B/SaaS Video Editor',
    metaDescription: 'Hire a B2B/SaaS Video Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a B2B video editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 63,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-motivational-content-editor',
    title: 'Hire a Motivational/Quotes Content Editor',
    metaDescription: 'Hire a Motivational/Quotes Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a motivational content editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 64,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-beauty-lifestyle-editor',
    title: 'Hire a Beauty/Lifestyle Content Editor',
    metaDescription: 'Hire a Beauty/Lifestyle Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a beauty lifestyle editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 65,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-true-crime-content-editor',
    title: 'Hire a True Crime/Storytelling Content Editor',
    metaDescription: 'Hire a True Crime/Storytelling Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a true crime content editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
  {
    id: 66,
    type: 'hire',
    funnelSide: 'creator',
    slug: 'hire-a-linkedin-video-editor',
    title: 'Hire a LinkedIn Video Content Editor',
    metaDescription: 'Hire a LinkedIn Video Content Editor. Learn how Kreatli Marketplace helps creators and clippers in the video editing marketplace.',
    primaryKeyword: 'hire a LinkedIn video editor',
    searchIntent: 'transactional',
    wave: 3,
    dependency: 'Needs validated demand + 5+ listings',
    status: 'draft',
    notes: 'Launch only once the niche has real listing density',
    minListingsRequired: 5,
    ctaHref: '/jobs/create',
  },
];
