export const CATEGORIES = [
  { label: 'Cars and vehicles', value: 'cars-and-vehicles' },
  { label: 'Comedy', value: 'comedy' },
  { label: 'Education', value: 'education' },
  { label: 'Entertainment', value: 'entertainment' },
  { label: 'Film and animation', value: 'film-and-animation' },
  { label: 'Gaming', value: 'gaming' },
  { label: 'How-to and style', value: 'how-to-and-style' },
  { label: 'Music', value: 'music' },
  { label: 'News and politics', value: 'news-and-politics' },
  { label: 'Non-profits and activism', value: 'non-profits-and-activism' },
  { label: 'People and blogs', value: 'people-and-blogs' },
  { label: 'Pets and animals', value: 'pets-and-animals' },
  { label: 'Science and technology', value: 'science-and-technology' },
  { label: 'Sport', value: 'sport' },
  { label: 'Travel and events', value: 'travel-and-events' },
] as const;
